version: '3.8'

networks:
  k6:
  grafana:
  prometheus:

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - k6
      - grafana
      - prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.1
    networks:
      - grafana
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  demoqa-performance-tests:
    image: demoqa-performance-tests:latest
    container_name: demoqa-performance-tests
    build: .
    networks:
      - k6
      - prometheus
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - BASE_URL
      - USER_NAME
      - PASSWORD
    depends_on:
      - prometheus
    volumes:
      - ./reports:/performance/reports
      - ./screenshots:/performance/screenshots