name: F

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.FUNCTIONAL_TESTING_IMAGE_NAME}}:$(date +%s) --tag ${{env.FUNCTIONAL_TESTING_IMAGE_NAME}}:latest

    - name: Run tests
      run: docker run --rm -e BASE_URL -e USER_NAME -e PASSWORD --name ${{env.FUNCTIONAL_TESTING_IMAGE_NAME}} ${{env.FUNCTIONAL_TESTING_IMAGE_NAME}}:latest
      env:
        BASE_URL: ${{ env.USER_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
