name: F

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.functional_testing_image_name}}:$(date +%s) --tag ${{env.functional_testing_image_name}}:latest

    - name: Run tests
      run: docker run --rm -e BASE_URL -e USER_NAME -e PASSWORD --name ${{env.functional_testing_image_name}} ${{env.functional_testing_image_name}}:latest
