name: F

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s) --tag $IMAGE_NAME:latest
      env:
        IMAGE_NAME: ${{vars.FUNCTIONAL_TESTING_IMAGE_NAME}}

    - name: Run tests
      run: docker run --rm -e BASE_URL -e USER_NAME -e PASSWORD --name $IMAGE_NAME $IMAGE_NAME:latest
      env:
        IMAGE_NAME: ${{vars.FUNCTIONAL_TESTING_IMAGE_NAME}}
        BASE_URL: ${{ vars.USER_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
